# Generated by Django 4.1.5 on 2023-01-25 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Brand name')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Catagpry name')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('paymentmethod', models.CharField(choices=[('Zcash', 'Zain Cash'), ('OnD', 'On Delivery')], max_length=120, verbose_name='Payment Method')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Total')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=120, verbose_name='Color name')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Masurunits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=120, verbose_name='Unit name')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('password', models.CharField(max_length=120, verbose_name='Password')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('price_currency', models.CharField(choices=[('USD', '$'), ('IQD', 'دينار')], default='USD', max_length=120)),
                ('quantety', models.IntegerField(default=1)),
                ('packigedimantions', models.CharField(blank=True, max_length=120, null=True, verbose_name='Demantions')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=120, null=True, verbose_name='Clothes Size')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.brand')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.category')),
                ('Color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.color')),
                ('Masur_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.masurunits')),
            ],
        ),
        migrations.CreateModel(
            name='Checkresite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantety', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('editdate', models.DateTimeField(auto_now=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodects.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodects.product')),
            ],
        ),
    ]
