# Generated by Django 4.1.5 on 2023-01-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naem', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('qty', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodects.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodects.category')),
            ],
        ),
    ]
