# Generated by Django 4.1.5 on 2023-01-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=120, verbose_name='Color name')),
            ],
        ),
        migrations.CreateModel(
            name='Masurunits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=120, verbose_name='Unit name')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=120, verbose_name='Size name')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='quantety',
        ),
        migrations.AddField(
            model_name='product',
            name='packigedimantions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Brand name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Catagpry name'),
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='Masurunits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.masurunits'),
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodects.size'),
        ),
    ]
