# Generated by Django 4.1.5 on 2023-01-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0002_color_masurunits_size_rename_qty_product_quantety_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='naem',
            new_name='name',
        ),
    ]
