# Generated by Django 4.1.5 on 2023-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0003_rename_naem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packigedimantions',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True, verbose_name='Demantions'),
        ),
    ]
