# Generated by Django 4.1.5 on 2023-01-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0004_alter_product_packigedimantions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.CharField(choices=[('USD', '$'), ('IQD', 'دينار')], default='USD', max_length=120),
        ),
    ]
