# Generated by Django 4.1.5 on 2023-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0005_product_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packigedimantions',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Demantions'),
        ),
    ]
