# Generated by Django 4.1.5 on 2023-01-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0006_alter_product_packigedimantions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Masurunits',
            new_name='Masur_units',
        ),
    ]
