# Generated by Django 4.1.5 on 2023-01-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodects', '0008_remove_product_size_delete_size_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('address', models.CharField(max_length=120, verbose_name='Address')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('paymentmethod', models.CharField(max_length=120, verbose_name='Payment Method')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Total')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=120, null=True, verbose_name='Clothes Size'),
        ),
        migrations.CreateModel(
            name='Checkresite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantety', models.IntegerField(default=1)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodects.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodects.product')),
            ],
        ),
    ]
